from .main_window_ui import Ui_MainWindow as UIMainWindow
from .dialog_edit_state_ui import Ui_Dialog_Edit_State as UIDialogEditState
from .dialog_show_graph_ui import Ui_Dialog_Show_Graph as UIDialogShowGraph